# paths
trajs_directory: ../data/trajs/
plns_directory: ../data/plns/
weather_directory: ../data/weather/
grib_directory: ../data/weather/grib/

# input_type
# 1 -> [latitude, longitude, altitude, northerly speed, easterly speed, northerly wind, easterly wind]
# 2 -> [latitude, longitude, altitude, northerly wind, easterly wind]
input_type: 2

levels:
  - 1000
  - 2000
  - 3000
  - 5000
  - 7000
  - 10000
  - 15000
  - 17500
  - 20000
  - 22500
  - 25000
  - 27500
  - 30000
  - 35000
  - 40000
  - 45000
  - 50000
  - 55000
  - 60000
  - 65000
  - 70000
  - 75000
  - 80000
  - 85000
  - 90000
  - 92500
  - 95000
  - 100000
