# training or prediction
train: True
# model_type:
# 0 -> seq2vec
# 1 -> seq2seq encoder-decoder
model_type: 0

# model
name: seq2vec_3LSTM512_1Dense_2TransConv_500epochs
# layers_list[0] -> RNN layers ("LSTM" or "GRU", (hidden state dimensions tuple))
# layers_list[1] -> Dense layers ((output dimensions tuple), (activations tuple))
# layers_list[2] -> Conv2DTranspose layers ((filters tuple), (kernels tuple), (padding tuple), (activations tuple))
layers_list:
  - ["LSTM", [512, 512, 512]]
  - [[576], ['elu']]
  - [[64, 1], [3, 3], [0, 1], ['elu', null]]
directory: ../models/
input_dim: 160
output_dim: 160
batch_size: 256
epochs: 500
learning_rate: 1.0e-3
beta_1: 0.9
beta_2: 0.999
# mean_squared_error
# binary_crossentropy
# weighted_mse
# yolo
loss: weighted_mse
l2_lambd: 0
nb_splits: 0
train_val_split: True
index_file: seq2vec

# inference
use_val: True
# plot_type:
# 0 -> plot_predict_ytensor
# 1 -> plot_error_dist
plot_type: 0
pred_dim: 160
